title: Boca do Lagarto - Casas de Aluguel
source: .
collections_dir: .
destination: ./public
baseurl: ""
url: https://bocadolagarto.com.br
lang: pt-BR
locale: pt_BR
google_analytics: "" # UA-111111111-1
social:
  name: Boca do Lagarto - Casas de Aluguel
  links:
    - https://www.instagram.com/bocadolagarto/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - server-local
  - docker
  - .github
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - app
  - .idea
